const $ = s => document.querySelector(s);
const csrf = $('#csrf').value;
let products = [], history = [], chart;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function note(text, bad=false){const n=$('#notice');n.className='alert '+(bad?'alert-danger':'alert-success');n.textContent=text;setTimeout(()=>n.classList.add('d-none'),4500);}
async function api(url, opts={}) {
 const headers = {'X-CSRF-Token':csrf, ...(opts.headers||{})};
 if(opts.body && !(opts.body instanceof FormData)) headers['Content-Type']='application/json';
 const r=await fetch(url,{...opts,headers}); let d={}; try{d=await r.json()}catch{}
 if(!r.ok) throw Error(d.error||`Request failed (${r.status})`); return d;
}
async function loadStats(){const d=await api('api/data.php?type=stats');$('#sProducts').textContent=d.products;$('#sTotal').textContent=d.total;$('#sDefects').textContent=d.defects;$('#sLoss').textContent='₹'+Number(d.loss).toLocaleString('en-IN',{maximumFractionDigits:2});}
async function loadProducts(){const d=await api('api/products.php');products=d.products;$('#productRows').innerHTML=products.map(p=>`<tr><td>${esc(p.product_code)}</td><td>${esc(p.name)}</td><td>₹${Number(p.unit_price).toFixed(2)}</td><td><button class="btn btn-sm btn-outline-info edit" data-id="${p.id}">Edit</button> <button class="btn btn-sm btn-outline-danger delete" data-id="${p.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="4">No products yet.</td></tr>';}
function clearProduct(){$('#productId').value='';$('#pCode').value='';$('#pName').value='';$('#pPrice').value='';}
$('#newProduct').onclick=()=>{clearProduct();$('#pCode').focus()};$('#cancelProduct').onclick=clearProduct;
$('#productRows').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const p=products.find(x=>x.id==b.dataset.id);if(b.classList.contains('edit')){$('#productId').value=p.id;$('#pCode').value=p.product_code;$('#pName').value=p.name;$('#pPrice').value=p.unit_price;location.hash='#products';}else if(b.classList.contains('delete')&&confirm('Delete this product?')){try{await api('api/products.php?id='+p.id,{method:'DELETE'});note('Product deleted.');await loadProducts();await loadStats();}catch(err){note(err.message,true)}}};
$('#productForm').onsubmit=async e=>{e.preventDefault();const id=$('#productId').value;const body={product_code:$('#pCode').value,name:$('#pName').value,unit_price:Number($('#pPrice').value)};try{await api('api/products.php'+(id?'?id='+id:''),{method:id?'PUT':'POST',body:JSON.stringify(body)});clearProduct();note('Product saved.');await loadProducts();await loadStats()}catch(err){note(err.message,true)}};
async function loadHistory(){const q=encodeURIComponent($('#historySearch').value);const d=await api('api/data.php?type=history&q='+q);history=d.rows;$('#historyRows').innerHTML=history.map(r=>`<tr><td>${esc(r.detected_at)}</td><td>${esc(r.detection_code)}</td><td>${esc(r.product_name)}</td><td>${esc(r.category)}</td><td>${Number(r.confidence).toFixed(1)}%</td><td>${esc(r.camera)}</td><td>${esc(r.status)}</td><td>₹${Number(r.estimated_loss).toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="8">No detections found.</td></tr>';const cats={};history.forEach(r=>cats[r.category]=(cats[r.category]||0)+1);if(chart)chart.destroy();chart=new Chart($('#categoryChart'),{type:'bar',data:{labels:Object.keys(cats),datasets:[{label:'Detections in loaded history',data:Object.values(cats)}]},options:{responsive:true,scales:{y:{beginAtZero:true}}}});}
$('#refreshHistory').onclick=loadHistory;let searchTimer;$('#historySearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadHistory().catch(e=>note(e.message,true)),250)};
$('#detectForm').onsubmit=async e=>{e.preventDefault();const f=$('#image').files[0];if(!f)return;const fd=new FormData();fd.append('image',f);fd.append('camera',$('#camera').value);$('#detectResult').textContent='Running detection…';try{const d=await api('api/detect.php',{method:'POST',body:fd});$('#detectResult').innerHTML=`<div class="alert alert-info">Result: <b>${esc(d.detection.category)}</b> · Confidence ${Number(d.detection.confidence).toFixed(1)}% · ${esc(d.detection.status)}</div>`;await loadHistory();await loadStats();}catch(err){$('#detectResult').textContent=err.message;}}
$('#alertForm').onsubmit=async e=>{e.preventDefault();try{await api('api/alerts.php',{method:'POST',body:JSON.stringify({severity:$('#severity').value,message:$('#alertMessage').value})});$('#alertMessage').value='';note('Alert added.');await loadAlerts()}catch(err){note(err.message,true)}};
async function loadAlerts(){const d=await api('api/alerts.php');$('#alertRows').innerHTML=d.alerts.map(a=>`<div class="border-bottom py-2"><b>${esc(a.severity)}</b> · ${esc(a.message)} <small class="text-secondary">${esc(a.status)} · ${esc(a.created_at)}</small> <button class="btn btn-sm btn-outline-success ack" data-id="${a.id}">Acknowledge</button></div>`).join('')||'No alerts.';}
$('#alertRows').onclick=async e=>{const b=e.target.closest('.ack');if(!b)return;try{await api('api/alerts.php?id='+b.dataset.id,{method:'PATCH',body:JSON.stringify({status:'Acknowledged'})});await loadAlerts()}catch(err){note(err.message,true)}};
async function loadMachines(){const d=await api('api/data.php?type=machines');$('#machineRows').innerHTML=d.machines.map(m=>`<tr><td>${esc(m.machine_code)}</td><td>${esc(m.name)}</td><td>${esc(m.status)}</td><td>${Number(m.health_score).toFixed(1)}%</td><td>${Number(m.availability).toFixed(1)}%</td></tr>`).join('')||'<tr><td colspan="5">No machines configured.</td></tr>';}
$('#exportCsv').onclick=()=>{const cols=['detected_at','detection_code','product_id','product_name','category','confidence','camera','status','estimated_loss'];const csv=[cols.join(','),...history.map(r=>cols.map(k=>'"'+String(r[k]??'').replace(/"/g,'""')+'"').join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='visionqc-detection-history.csv';a.click();URL.revokeObjectURL(a.href);};
$('#logout').onclick=async()=>{try{await api('api/auth.php?action=logout',{method:'POST',body:'{}'});location.href='index.php'}catch(e){note(e.message,true)}};
document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('#nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
(async()=>{try{await Promise.all([loadStats(),loadProducts(),loadHistory(),loadAlerts(),loadMachines()])}catch(e){note(e.message,true)}})();
